### ISSUE TITLE
View resources button does not fix to bottom of card

### ISSUE THREAD

**Issue by arp99** [rishipurwar1/coding-space#104]
**Describe the bug**
View resources card does not fix to the bottom of card if the screen size is changed

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the live website
2. Click on resources
3. You will notice view resources button is not fixed to the bottom of every card

**Expected behaviour**
The view resources button should fix to the bottom of every card

**Screenshots**

![same_issue_resources](https://user-images.githubusercontent.com/47218246/135824787-e984e591-68a8-4ed1-9c6d-d32c75a115b7.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 22

**Comment by rishipurwar1** [comment]
Feel free to star a repo

**Comment by rishipurwar1** [comment]
I think the same issue is in the solution cards as well.
Please fix that as well.

**Comment by arp99** [comment]
> I think the same issue is in the solution cards as well. Please fix that as well.
I didn't notice it while testing as there was only one card, could you please create an issue and assign me?

**Comment by rishipurwar1** [comment]
> > I think the same issue is in the solution cards as well. Please fix that as well.
> 
> I didn't notice it while testing as there was only one card, could you please create an issue and assign me?

Can you please create an issue by yourself, I'll assign you.
