### ISSUE TITLE
Fix card image height

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#108]
**Describe the bug**
In this task, you need to fix the height of the image in all the cards.

**To Reproduce**

1. Open the website on Safari Browser https://www.codingspace.codes/
2. Scroll to the challenge card(Challenge, solutions)
3. See error

**Expected behavior**
The height of the image should be the same on every browser/OS

**Screenshots**
<img width="800" alt="Screenshot 2021-10-04 at 6 45 38 PM" src="https://user-images.githubusercontent.com/57035408/135857924-bba0fb60-b6f9-43eb-ae41-0d3a6e7a7cb9.png">

**Desktop (please complete the following information):**

- OS: macOS Big Sur v11.6
- Browser: safari
- Version: 15.0

**Comment by a-muk** [comment]
Hello! I wld like to work on this issue. Can it be assigned to me?

**Comment by rishipurwar1** [comment]
@a-muk assigned to you.
Please share the screenshot of the changes before committing your code.

**Comment by aushwin** [comment]
Can I also work on the issue ?

**Comment by rishipurwar1** [comment]
> Can I also work on the issue ?

already assigned to @a-muk, you can pick different issue.

**Comment by rishipurwar1** [comment]
Still showing to me
<img width="1193" alt="Screenshot 2021-10-10 at 6 54 13 PM" src="https://user-images.githubusercontent.com/57035408/136697678-a58958ae-46ff-4ffa-a981-a8123db9455c.png">

**Comment by rishipurwar1** [comment]
> On Safari browser also, its showing the same

Browser Version?

**Comment by a-muk** [comment]
sir, I tried a lot but am not sure how to do this one. You can assign it to someone else 🙏🏻

**Comment by rishipurwar1** [comment]
@a-muk No Problem
