### ISSUE TITLE
Add Hover Effect for Github Sign up Button

### ISSUE THREAD

**Issue by random3900** [rishipurwar1/coding-space#128]
Currently, the 2 github signup buttons on the home page do not have any hover effects on them. 
![image](https://user-images.githubusercontent.com/61742380/136146471-75ae2950-9d9a-4abe-a8db-8e1577abc531.png)
![image](https://user-images.githubusercontent.com/61742380/136146582-8d63315b-e559-44a8-a985-dccbf009576c.png)

Hover effects need to be added similar to [this](https://supabase.io/)

**Comment by random3900** [comment]
Hero Button without hover
![image](https://user-images.githubusercontent.com/61742380/136190441-17779c49-1ec9-4797-997f-8578da8bb9f2.png)

Hero Button with hover 
![image](https://user-images.githubusercontent.com/61742380/136190550-f8ceaf19-475b-4ef9-9677-1034481f8a28.png)

Navbar button without hover
![image](https://user-images.githubusercontent.com/61742380/136190588-c03cff05-789e-4113-bb7a-0627896c628c.png)

Navbar button with hover
![image](https://user-images.githubusercontent.com/61742380/136190637-56de0b4c-61c5-4cb7-983e-3403e986c9a3.png)

@rishipurwar1  hope this is fine, please let me know if I can create a PR

**Comment by rishipurwar1** [comment]
> Hero Button without hover ![image](https://user-images.githubusercontent.com/61742380/136190441-17779c49-1ec9-4797-997f-8578da8bb9f2.png)
> 
> Hero Button with hover ![image](https://user-images.githubusercontent.com/61742380/136190550-f8ceaf19-475b-4ef9-9677-1034481f8a28.png)
> 
> Navbar button without hover ![image](https://user-images.githubusercontent.com/61742380/136190588-c03cff05-789e-4113-bb7a-0627896c628c.png)
> 
> Navbar button with hover ![image](https://user-images.githubusercontent.com/61742380/136190637-56de0b4c-61c5-4cb7-983e-3403e986c9a3.png)
> 
> @rishipurwar1 hope this is fine, please let me know if I can create a PR

It just looks OK to me in the pictures.

**Comment by rishipurwar1** [comment]
Try to use different background colors
