### ISSUE TITLE
Is there anyway I can contribute in this project?

### ISSUE THREAD

**Issue by aryan2621** [rishipurwar1/coding-space#129]

**Comment by rishipurwar1** [comment]
@aryan2621 yes there are so many ways to contribute to this project. You can pick an issue from the github issue page or create an issue(you can easily find UI bug). You can also help us to write new challenge. You can also create new challenges for the codingspace community.

Please join the codingspace [discord server](https://discord.com/invite/FYSQUEw6xP).
Please give a star to this repo.

**Comment by rishipurwar1** [comment]
I am going to close this issue but you can reply on this.
