### ISSUE TITLE
Add a hover effect on any card

### ISSUE THREAD

**Issue by tausifaman222** [rishipurwar1/coding-space#132]
**Is your feature request related to a problem? Please describe.**
Currently, the website doesn't have any hover effect on any card. So, I would like to add a cool hover effect to the card.

**Describe the solution you'd like**
My suggestions : 
- Add a levitating effect on hovering over the card.
- Cool Shadow on hover

**Additional context**
I am talking about this card which currently lacks any hover effect.
![SS](https://user-images.githubusercontent.com/72369808/136429653-e1b62e16-2188-4849-a459-f7d460263dc9.JPG)

**Comment by Preetojha08** [comment]
Hey @rishipurwar1, I also want to work on this issue this is a great opportunity for me.

**Comment by rishipurwar1** [comment]
Hey @Preetojha08 
You can also work on this but you need to work on the solutions card instead of the challenge but please make sure you and @tausifaman222 adding the same hover effect.

You can discuss your ideas in the codingspace [discord server](https://discord.com/invite/FYSQUEw6xP) in the codingspace-features-discussion channel.

Feel free to give a star to the repository.

**Comment by rishipurwar1** [comment]
> @rishipurwar1 Please review and assign this issue to me. Thanks

Assigned to you
Before committing your code, please show a screenshot of the changes and try to change a box-shadow property on hover, I think It would look good.
and please make a PR to the development branch, not in the main branch.

**Comment by tausifaman222** [comment]
@rishipurwar1 Please see the preview below and suggest if any customizations are required.

https://user-images.githubusercontent.com/72369808/139490841-cbf3fca1-6fe2-492d-9032-fca3ebf03ccc.mp4

**Comment by rishipurwar1** [comment]
I just added a new challenge in the development firebase project.
Can you please share a screen recording of the hover effect on different screen sizes? 
and Is the first card overlapping over the second card on hover?

**Comment by tausifaman222** [comment]
@rishipurwar1 Sure, I have shared the screen recording. Please take a look and give suggestions

https://user-images.githubusercontent.com/72369808/139538049-ff5f4c5f-576d-4296-9e3d-92f48f679a35.mp4

**Comment by rishipurwar1** [comment]
everything looks good to me!

Is there any need to add the `cursor: pointer` property to the whole card? We didn't attach a link to the whole card, so, onclick nothing will happen.

**Comment by tausifaman222** [comment]
No, practically not needed. If you suggest, I can remove it. Only, view challenge part needed the pointer.
Thanks for suggestions
@rishipurwar1
