### ISSUE TITLE
The website should use react-firebase-hooks to clean the code

### ISSUE THREAD

**Issue by Prashoon123** [rishipurwar1/coding-space#135]
# Overview
## Is your feature request related to a problem? Please describe.
The firebase hooks seem pretty complicated so if we implement react-firebase-hooks then the code will be pretty simple to work with.

## Describe the solution you'd like
First of all, we will upgrade the firebase version to 9 as react-firebase hooks only support Firebase v9+. Moreover, we will use the compat version the syntax remains the same. Once Firebase is properly setup then we will implement the react-firebase-hooks logic.

# Success criteria

* The code will be clean so that developers can easily contribute to the project.

# User stories
How the product should work for various user types.
 
## As a user

* There won't be any substantial change.

## As a front end engineer

* The code will be very easy to work with.
 
# Scope
## Requirements
Current project requirements.

* We will have to upgrade Firebase to v9
* We will have to install react-firebase-hooks
 
## Future work
Future requirements.
 
* Check if react-firebase-hooks start supporting the normal version of Firebase.

## Non-requirements
All the Firebase syntax will remain the same.

**Comment by Prashoon123** [comment]
@rishipurwar1 can you please assign this to me?

**Comment by rishipurwar1** [comment]
Hey @Prashoon123 
I also want to refactor the code of firestore hook.
We'll work together on this issue, just give me some time. I am a little busy these days.
For now, write things down how are you going to make changes and what is the impact of those changes on the website(i.e. improve performance).

**Comment by rishipurwar1** [comment]
> > # Overview
> > ## Is your feature request related to a problem? Please describe.
> > The firebase hooks seem pretty complicated so if we implement react-firebase-hooks then the code will be pretty simple to work with.
> > ## Describe the solution you'd like
> > First of all, we will upgrade the firebase version to 9 as react-firebase hooks only support Firebase v9+. Moreover, we will use the compat version the syntax remains the same. Once Firebase is properly setup then we will implement the react-firebase-hooks logic.
> > # Success criteria
> > 
> > * The code will be clean so that developers can easily contribute to the project.
> > 
> > # User stories
> > How the product should work for various user types.
> > ## As a user
> > 
> > * There won't be any substantial change.
> > 
> > ## As a front end engineer
> > 
> > * The code will be very easy to work with.
> > 
> > # Scope
> > ## Requirements
> > Current project requirements.
> > 
> > * We will have to upgrade Firebase to v9
> > * We will have to install react-firebase-hooks
> > 
> > ## Future work
> > Future requirements.
> > 
> > * Check if react-firebase-hooks start supporting the normal version of Firebase.
> > 
> > ## Non-requirements
> > All the Firebase syntax will remain the same.
> 
> @rishipurwar1 I have filled the template in the description of this issue.

Great
Will take a look!
