### ISSUE TITLE
On click profile modal should get close

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#138]
**Describe the bug**
In the profile menu, when we click on my solutions button, it doesn't close the profile modal

**To Reproduce**

1. log in to the website
2. Click on your profile picture
3. then click on my solutions
4. See an error

**Expected behavior**
When we click on my solutions button or outside that profile modal, it should get close.

**Screenshots**

https://user-images.githubusercontent.com/57035408/136691573-b53e1caf-a8a8-463e-834a-c91f319f094b.mov

**Comment by programmerraja** [comment]
@rishipurwar1 can i work on this bro

**Comment by rishipurwar1** [comment]
@programmerraja yes, you can work on this.

**Comment by RashiSingh20** [comment]
@rishipurwar1 Hey Can you please assign it to me? I would like to work on this.

**Comment by rishipurwar1** [comment]
@RashiSingh20 you can work on this

**Comment by RashiSingh20** [comment]
Yes, I created a project on firebase and used the config file . My email id:  rashisingh2620@gmail.com @rishipurwar1

**Comment by rishipurwar1** [comment]
> @rishipurwar1 hey, recently I implement this in my project. using a simple custom hooks. Can i add this

Yes, You can work on this but I think I already have a setOpen something in the code that will help you in achieving this functionality.

**Comment by Bivas-Biswas** [comment]
i know. but when we click outside the components , it must be close. For
this I used a custom hooks before.

**Comment by rishipurwar1** [comment]
You can make use of the same thing for that as well! You need to give a transparent background to the outer div and then that div should occupy the cover the whole content and then add onClick event to that div, so, when the user clicks on the outer part of the modal then it'll run set setIsOpen(false). I did the same for the delete solution button.

**Comment by Bivas-Biswas** [comment]
okey, got it
