### ISSUE TITLE
Add css style to scrollbar

### ISSUE THREAD

**Issue by Kunal0007** [rishipurwar1/coding-space#155]
Add style to the scrollbar matching with the theme.

Can I work on this issue??

**Comment by rishipurwar1** [comment]
Hello @Kunal0007 really sorry for the late reply. Do you still want to work on this?

**Comment by Kunal0007** [comment]
> Hello @Kunal0007 really sorry for the late reply. Do you still want to work on this?

Yes

**Comment by rishipurwar1** [comment]
> > Hello @Kunal0007 really sorry for the late reply. Do you still want to work on this?
> 
> Yes

Assigned to you!

Note: Please make a PR to the development branch NOT in the main branch and test your changes on all the pages before making a PR.
