### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [rishipurwar1/coding-space#173]
👋 Hi @rishipurwar1,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Collaborate` repo. This means that you want to invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Collaborate` CX submission on June 1, 2022.

After reviewing your repository, it already meets our standards for submission! 🎉 

If you have any questions, please feel free to leave a comment, otherwise, I will contact you when it is time to submit your project! :octocat:

**Comment by rishipurwar1** [comment]
Hello Eric👋,

Thanks for reviewing my repository🙏.
I'm looking forward to submitting it as well.
