### ISSUE TITLE
Login modal design is broken and not closable at small screen.

### ISSUE THREAD

**Issue by ParasSolanki** [rishipurwar1/coding-space#177]
**Describe the bug**
At small screen devices no way to close the login modal and design is also broken.

**To Reproduce**

1. You should not be logged in if you are logged in log out.
2. Go to any [Challenge details page](https://www.codingspace.codes/challenge/2m645LgvLil4GqPNzSFL).
3. Open this page on mobile device which has resolution below 670px or resize your browser window below 670px.
4. Click on Download button.
5. See modal which is not closable on small devices and design is broken.

**Expected behavior**
The modal should be closable in small devices and design should be fixed show modal in the middle. 

**Screenshots**
At mobile screen.
![small-screen-design-broken](https://user-images.githubusercontent.com/62164346/173612230-2520834b-8b18-4fdc-8e81-4a873f1962a5.jpg)
At medium tablet screen
![medium-screen-design-issue](https://user-images.githubusercontent.com/62164346/173612647-34e1ea6c-9dac-44be-9fd7-4484bac454eb.JPG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome, Edge
- Version: 102.0, 102.0.1245.41 (Edge)

**Smartphone (please complete the following information):**

- Device: Redmi note 7s
- OS: MIUI 12
- Browser: Chrome
- Version: 101.0

**Additional context**
- Instead of relative positioning we should add fixed position so modal. we could center align modal using below css. we could achieve same css with tailwind utility classes. 

```css
position: fixed;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
```

**Comment by rishipurwar1** [comment]
Hello Paras,
Thanks for reporting this issue.

Would you like to work on this issue?

**Comment by ParasSolanki** [comment]
Yeah would love to help..
