### ISSUE TITLE
Delete modal is not visible

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#189]
**Describe the bug**
The delete modal doesn't visible completely when we open it in the middle of the page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any of your submitted solutions.
2. Scroll down to the website preview.
3. Click on the delete icon
4. See an error

**Expected behaviour**
It should be on top of everything and completely visible when a user clicks on the delete button.

**Screenshots**

<img width="944" alt="Screenshot 2022-10-02 at 11 13 01 AM" src="https://user-images.githubusercontent.com/57035408/193439966-9fe8b084-cc40-475e-9870-74db2e7ce840.png">

**Comment by JatinSingh08** [comment]
Hey @rishipurwar1  Please assign this to me.

**Comment by rishipurwar1** [comment]
> Hey @rishipurwar1 Please assign this to me.

Assigned to you.

Note: Please make a PR to the development branch **NOT** in the main branch and test your changes on all the pages where we're using this component.

**Comment by rishipurwar1** [comment]
Looking forward to seeing your PR! Feel free to give a star⭐️ to this repo.

**Comment by JatinSingh08** [comment]
Yes, Thanks @rishipurwar1 .

**Comment by JatinSingh08** [comment]
@rishipurwar1  Can you please tell what's the file name for the delete solution component?

**Comment by rishipurwar1** [comment]
> @rishipurwar1 Can you please tell what's the file name for the delete solution component?

File: https://github.com/rishipurwar1/coding-space/blob/main/src/components/reusable/ConfirmationModal.js

**Comment by JatinSingh08** [comment]
Okay, got it.....Thanks.

**Comment by JatinSingh08** [comment]
@rishipurwar1  can you guide me on how setup the database for challenges? I'm unable to run the app so that I can delete one solution to check whether my code is running fine or not.

**Comment by rishipurwar1** [comment]
> @rishipurwar1 can you guide me on how set up the database for challenges? I'm unable to run the app so that I can delete one solution to check whether my code is running fine or not.

can you please share your email id here or dm me on the [codingspace discord](https://discord.com/invite/FYSQUEw6xP) server so that I can add you to our database?

**Comment by JatinSingh08** [comment]
Dmed you on discord server.

**Comment by rishipurwar1** [comment]
@JatinSingh08 Any updates??
