### ISSUE TITLE
Profile photo modal not completely visible on mobile screen.

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#190]
**Describe the bug**
The Profile photo modal doesn't completely visible on a mobile screen, the waving hand emoji icon overlaps the modal. (See screenshot)

**To Reproduce**
Steps to reproduce the behaviour:

1. Open any page of the website on mobile screen.
2. Click on the Avatar Modal (Please log in first)
3. See error

**Expected behaviour**
The profile photo modal should be on top of everything and completely visible when a user clicks on the profile photo.

**Screenshots**
<img width="413" alt="Screenshot 2022-10-02 at 11 20 21 AM" src="https://user-images.githubusercontent.com/57035408/193440281-9e652085-efca-4353-b2e9-1645ea54474e.png">

**Comment by drishit96** [comment]
Hi @rishipurwar1, I'd like to work on this

**Comment by rishipurwar1** [comment]
@drishit96 Assigned to you.

Note: Please make a PR to the development branch NOT in the main branch and test your changes on all the pages where we're using this component before making a PR.

**Comment by rishipurwar1** [comment]
Looking forward to seeing your PR! Feel free to give a star⭐️ to this repo.
