### ISSUE TITLE
Add a loading indicator to the delete button

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#191]
**Describe the improvement**
Right now, when a user opens a delete modal on the solution details page and clicks on the delete button, it immediately redirects the user to the homepage without showing a delete indicator on the button.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any of your submitted solutions.
2. Click on the delete icon
3. Click on the delete button
4. See an issue

**Expected behaviour**
It should show a delete loading indicator when a user clicks on the delete button and after deleting it should redirect the user to the homepage.

You can see a similar loading indicator on the solution submission page, click on the submit button and see the loading indicator and you can see the code of that [part here](https://github.com/rishipurwar1/coding-space/blob/3fee7eeb94520531011238d8038ff1021cddb472/src/components/solutions/SolutionForm.js#L137).

**Comment by gogoiakash2311** [comment]
hey @rishipurwar1 can you assign this to me?

**Comment by Akshay9607** [comment]
Hello i want to work on this issue

**Comment by Chitvan14** [comment]
Hi, I will be happy to solve this issue, please assign this to me.

**Comment by Rahul-Palahwat** [comment]
Hey @rishipurwar1 as this is going to be my first contribution , can you please assign this issue to me

**Comment by rishipurwar1** [comment]
Thank you all for showing your interest in contributing to this issue.

But I can only assign this to one(first come first serve basis). I'll open more issues, please keep an eye on the issue page of this repo.

@gogoiakash2311 assigned to you!

Looking forward to seeing your PR!
Feel free to give a star✨ to this repo, everyone!

**Comment by gogoiakash2311** [comment]
Thanks, @rishipurwar1 for assigning me for this. Already gave a start to this repo!
