### ISSUE TITLE
Fix skeleton loading card

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#25]
## To Reproduce
1. Go to any of the pages and see the size difference between skeleton cards and actual cards.

## Expected behavior
The size of both the cards should be the same to make everything look similar before and after loading.

If anyone wants to work on this issue, please let me know in the comment.

**Comment by RosarNicolas** [comment]
Hello, I would like to try working on this issue is it possible?

**Comment by rishipurwar1** [comment]
@RosarNicolas assigned to you!
Please create a new branch and push your code to the development branch not in main branch.

**Comment by RosarNicolas** [comment]
I started looking at the issue and have few questions before starting to code.
1. The challenges cards are using grid and the skeleton ones are using flex. Is there a reason for it?

2. The main size differences are from the height so does something like this would work? (with the pulse grey animation)

![Challenge_card_skeleton](https://user-images.githubusercontent.com/32072799/134178924-ade13c57-4fa7-47f2-8d86-504c4edb4f1d.png)

**Comment by rishipurwar1** [comment]
> * The challenges cards are using grid and the skeleton ones are using flex. Is there a reason for it?
> *
No, there is no reason for it. You can layout the skeleton card using CSS Grid or if you don't have time, you can leave it for now, only focus on skeleton cards.



> 2\. The main size differences are from the height so does something like this would work? (with the pulse grey animation)

It looks good but I would suggest adding more skeletons for paragraphs, as there is so much whitespace.

> 1. Is there a way for me to add a challenge to my firebase database?

No, there is no way for you to add a challenge but I can add you to my firebase account to access data for the development purpose, share you email id over here or you can dm me on our [discord community server](https://discord.gg/FYSQUEw6xP) or on [Twitter](https://twitter.com/thefierycoder)
