### ISSUE TITLE
Downloading Other Challenge Starter Code

### ISSUE THREAD

**Issue by sahilatahar** [rishipurwar1/coding-space#255]
I want to Solve the challenge "Toast Notification Component" but I download the Started code It was "Profile Card Component" starter code which was next challenge.

**To Reproduce**

1. Go to 'https://www.frontendpro.dev/frontend-coding-challenges/toast-notification-component-mHFR9GcTlWSyG8dO32Ok'
2. Click on 'Start Challenge'
3. Click on "Download Starter Code"
4. See Profile Card Component starter file will be download instead of Toast Notification Component.

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version Latest

**Comment by Drish-xD** [comment]
Same with `Newsletter Card Component`

It's downloading multi-step-form starter code

**Comment by sahilatahar** [comment]
Issue is not resolved but I find figma link:
[Toast-Notification-Component figma link](https://www.figma.com/file/nTyjZcdiJmjKqKwRhGwWqp/Toast-Notification-Component?node-id=9%3A2&mode=dev)

**Comment by rishipurwar1** [comment]
Hello @sahilatahar @Drish-xD Thanks for reporting the issues. I've fixed both the issues. Please let me know if you face any other issues.

P.S: Sorry for the late reply.

**Comment by sahilatahar** [comment]
Thanks
