### ISSUE TITLE
Card and button lack hover effect

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#26]
## Describe the improvement
If you hover over any of the cards and buttons, they don't show a hover effect.

## Expected behavior
Add a hover effect to cards and buttons to make things smoother.

If anyone wants to work on this issue, please let me know in the comment.

**Comment by mehmettemel** [comment]
I can work on it

**Comment by rishipurwar1** [comment]
@mehmettemel assigned to you.

**Comment by rishipurwar1** [comment]
You need to add to all the cards(challenges, solutions, resources)

**Comment by mehmettemel** [comment]
I have created firestore project for .env but cannot reach firestore data backend.I m only seeing skeleton cards

**Comment by rishipurwar1** [comment]
Hey @mehmettemel ,

Can you please share your email id from which you created the firebase project, so I can give you access to the data?
If you don't want to share your email id over here you can message me on [LinkedIn](https://www.linkedin.com/in/thefierycoder/) or [Twitter](https://twitter.com/thefierycoder).

**Comment by rishipurwar1** [comment]
Hey @mehmettemel 
Which type of hover effect are you planning to add on cards and buttons?

**Comment by mehmettemel** [comment]
I am planning to  change the background and text color of the card while hovering.I m not gonna change the button background color just make button text color more lighter.

**Comment by rishipurwar1** [comment]
> I am planning to change the background and text color of the card while hovering.I m not gonna change the button background color just make button text color more lighter.

Instead of changing the background and text color. I would suggest you change the box shadow value or scale up the cards on hover.
or checkout example-2 for[ inspiration](https://csshint.com/css-card-hover-effects/).

**Comment by rishipurwar1** [comment]
I would suggest you explore more examples for inspiration then let me know.

**Comment by rishipurwar1** [comment]
Feel free to give a Github star⭐️ to this repo.

**Comment by rishipurwar1** [comment]
@mehmettemel do you have any experience with eslint and prettier?

**Comment by mehmettemel** [comment]
yeah.you can watch traversy media video for this

**Comment by rishipurwar1** [comment]
@mehmettemel are you working on this issue?

**Comment by aman-sukhwal-7** [comment]
I can work on it!

**Comment by SAHU-01** [comment]
If this issue is open i'd like to work on it!

**Comment by rishipurwar1** [comment]
@aman-sukhwal-7 are you working on this issue?

**Comment by rishipurwar1** [comment]
@SAHU-01 If you want, you can work with @aman-sukhwal-7 on this issue.

**Comment by SAHU-01** [comment]
> @SAHU-01 If you want, you can work with @aman-sukhwal-7 on this issue. Both of you can divide this task, lets say you can work on a solutions card or resources card and aman can work on a challenges card.

@aman-sukhwal-7 lets dicuss and split the work,if it's ok with you!

**Comment by aman-sukhwal-7** [comment]
Actually I already resolved this issue!

**Comment by SAHU-01** [comment]
> Actually I already resolved this issue!

it's ok then not an issue!

**Comment by SAKSHAM-SINGH130** [comment]
I can fix this bug very easily.

**Comment by rishipurwar1** [comment]
@tausifaman222 please first show me changes before committing it and make a pr to the development branch and only commit those files in which you make changes, don't commit package.json and package-lock.json unless you make changes in these files.

**Comment by imps1001** [comment]
Hey @rishipurwar1, I can work on this issue if this is still open.

**Comment by SAKSHAM-SINGH130** [comment]
there are some specific codes for it. I can fixed this issue

**Comment by rishipurwar1** [comment]
> there are some specific codes for it. I can fixed this issue

Issue is fixed now.
