### ISSUE TITLE
Write caching logic(useSwr hook)

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#27]
## Problem statement
Right now codingspace doesn't have a way to cache data to load things faster.

## Describe the solution you'd like
I want to add a useSwr hook to cache the data to make the website load faster.

## Success criteria
The criteria must be met in order to consider this feature a success. 
- Load times reduced at least 20%, ideally more

## User stories
How the product should work for various user types.

### As a user
- I want my search queries to return results quickly
- So I can get my work done faster

### As a front end engineer
- I expect my queries to be cached on the back end
- So the front end can be as fast as possible

If anyone wants to work on this issue, please let me know in the comment section.

**Comment by Bivas-Biswas** [comment]
do you refer this [swr](https://swr.vercel.app/) ?

**Comment by rishipurwar1** [comment]
> do you refer this [swr](https://swr.vercel.app/) ?

Yes

**Comment by Bivas-Biswas** [comment]
Hey, I want to work on this. But First I need to learn this. So it takes some time.

**Comment by rishipurwar1** [comment]
Take your time.
Assigned to you

**Comment by Bivas-Biswas** [comment]
oke

**Comment by Bivas-Biswas** [comment]
how I see the login page in my system ?

**Comment by rishipurwar1** [comment]
There is no login page on the website.

**Comment by imps1001** [comment]
I also wants to work on this issue.

**Comment by rishipurwar1** [comment]
@Bivas-Biswas are you working on this one?

**Comment by imps1001** [comment]
Hey @rishipurwar1, kindly assign this to me

**Comment by rishipurwar1** [comment]
@imps1001 you can work on this with @Bivas-Biswas
