### ISSUE TITLE
Create a Join Discord Community button

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#28]
## Problem statement
Right now there is no way to join codingspace discord community.

## Describe the solution you'd like
Add a join discord community button on the website so, user can join the community.

## Success criteria
The criteria must be met in order to consider this feature a success. 
- More users become a part of our community.

## User stories
How the product should work for various user types.

### As a user
- I want a platform where I can ask my doubts/queries directly
- So I can get my answers fast

If anyone wants to work on this issue, please let me know in the comment section.

**Comment by mohammedrehan275** [comment]
I want to work on this issue.

**Comment by rishipurwar1** [comment]
@mohammedrehan275 assigned to you
Please let me know where are you going to add the button before starting coding it.

**Comment by mohammedrehan275** [comment]
How will it look adjacent to the signup with github button.
or let me know if you have any thoughts on this

**Comment by rishipurwar1** [comment]
for desktop, I would suggest you to add on the bottom of the sidebar.

**Comment by mohammedrehan275** [comment]
below resources and roadmap?

I will start working on it

**Comment by rishipurwar1** [comment]
> below resources and roadmap?
> 
> I will start working on it

yes

**Comment by rishipurwar1** [comment]
Feel free to give a Github Star⭐️ to this repo.

**Comment by tabassum2507** [comment]
Is this issue still open?

**Comment by rishipurwar1** [comment]
Hello @tabassum2507 👋

Welcome to the community!🎉
It's open but @mohammedrehan275 is working on it.
You can pick any other issues or create your own one if you find any bug on the website.
