### ISSUE TITLE
Typo in the How it works section

### ISSUE THREAD

**Issue by mohammedrehan275** [rishipurwar1/coding-space#32]
**Describe the bug**
There's a typo in the **how it works** section. The word access is misspelled as excess.

**Screenshots**

![Screenshot (4)](https://user-images.githubusercontent.com/65021509/134156224-ed110c2e-00ff-486c-89c9-fabd4f7283b7.png)

**Comment by YashKamboj** [comment]
You doing it or can i work on it??

**Comment by YashKamboj** [comment]
> > You doing it or can i work on it??
> 
> You can work on it

Thnx

**Comment by YashKamboj** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/75125203/134230895-8f5fd44c-50dd-456e-9211-e2247d419896.png)
Hey this error is showing without any changes, pls help.

**Comment by mohammedrehan275** [comment]
> ![Screenshot (77)](https://user-images.githubusercontent.com/75125203/134230895-8f5fd44c-50dd-456e-9211-e2247d419896.png)
> Hey this error is showing without any changes, pls help.

Add .env file in the root directory and enter the firebase config details in the env file.

The process is written in the readme file.

**Comment by rishipurwar1** [comment]
Create your own firebase project and then copy-paste your config info into
the .env file as mentioned in the readme.

>

**Comment by YashKamboj** [comment]
Ok thnx. I was making .env in src folder 😂😂
