### ISSUE TITLE
Fix solution details page blank screen

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#48]
About the bug
The solution details page should show a loading state(loader) instead of a blank page while content is loading.

To Reproduce

Go to any of the solution details pages and see the difference between the loading state and after loading state.
See an error
Expected behavior
It should show a loading animation(either an SVG loader or a skeleton loading animation) to fill up blank space, so users can have a better user experience.

Screenshot
<img width="1440" alt="Screenshot 2021-09-24 at 8 41 34 PM" src="https://user-images.githubusercontent.com/57035408/134698526-ad408c2c-5582-4f6d-9cbd-f3a0c1134229.png">

You can use this loader `/src/assets/animated_illustration/loader.json`
If anyone wants to work on this task, please let me know in the comment.

**Comment by wsameer** [comment]
@rishipurwar1 I can extend my fix for #24 and resolve this too. What say?

**Comment by rishipurwar1** [comment]
Yes! you can
