### ISSUE TITLE
Make footer stick to bottom of the page

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#62]
**Describe the bug**
When the content of the page is less, then the footer gets to stretch to fill the space.

**To Reproduce**

1. Go to the Roadmaps page
2. See footer

**Expected behavior**
It should stick to the bottom when the content of the page is less but when the content is enough then it should be scrollable.

**Screenshots**
<img width="1440" alt="Screenshot 2021-09-25 at 4 00 37 PM" src="https://user-images.githubusercontent.com/57035408/134772519-abafa977-a0f0-4efb-80c4-332cb133b4a9.png">

If anyone wants to work on this task, please let me know in the comment.

**Comment by aman-sukhwal-7** [comment]
I can work on it!

**Comment by aman-sukhwal-7** [comment]
I can work on it!

**Comment by rishipurwar1** [comment]
@aman-sukhwal-7 assigned to you

**Comment by sakuraixiao** [comment]
can i not work on it, if it is assigned to someone?

**Comment by rishipurwar1** [comment]
Hey @sakuraixiao,
@aman-sukhwal-7 already fixed this issue [in this pull request](https://github.com/rishipurwar1/coding-space/pull/67).
You can work on other issues.
