### ISSUE TITLE
Navigating through navbar on small screen.

### ISSUE THREAD

**Issue by aman-sukhwal-7** [rishipurwar1/coding-space#66]
**Describe the bug**
The side navbar doesn't close on clicking the other section.  

**To Reproduce**

1. Open the website on a small screen.
2. Click on the nav button.
3. Click on any nav link.

**Expected behavior**
It must get closed itself after clicking on any nav link.

**Comment by Bivas-Biswas** [comment]
can i work on this ?

**Comment by Bivas-Biswas** [comment]
can i work on this ?

**Comment by rishipurwar1** [comment]
@aman-sukhwal-7 are you working on this issue?

**Comment by Bivas-Biswas** [comment]
@rishipurwar1 
![image](https://user-images.githubusercontent.com/75929842/135510887-edfc5f85-cee0-473d-bf75-8bb059d999b6.png)
How can i get this, i am not familiar with firebase.

**Comment by rishipurwar1** [comment]
Hey @Bivas-Biswas,
Share your email here or you can DM me on Twitter or on our discord server. I'll give you access to the firebase db and then copy and paste your credentials from [here](https://console.firebase.google.com/).

**Comment by aman-sukhwal-7** [comment]
> @aman-sukhwal-7 are you working on this issue?

yes

**Comment by rishipurwar1** [comment]
Hey @ghozt777
Now, you can make PR.
please update your code first in the development branch and then commit only those files in which you made changes.
