### ISSUE TITLE
Issue in readme.md

### ISSUE THREAD

**Issue by shreyaansjain06** [rishipurwar1/coding-space#68]
Readme.md does not properly tells the beginners how to use it i can make the changes if you assign this issue to me

**Comment by rishipurwar1** [comment]
Hey @shreyaansjain06,

Welcome to the community,
What kind of changes would you like to make in Readme?
According to me, "how to access the firebase data" need proper documentation in the readme.md i.e. how do contributors get access to the firebase db?

**Comment by shreyaansjain06** [comment]
No i was talking about installation steps 
- fork the project is not present
- clone link is not correct
Some changes like that i was talking about that 
You can assign this issue if you understand what i mean

**Comment by rishipurwar1** [comment]
> * fork the project is not present

Yes, you're right fork step is missing but the cloning step is there.
You can add a fork step to the readme.md

**Comment by shreyaansjain06** [comment]
I have made the pr kindly check it and give it a label of hactoberfest-accepted and hactoberfest-2021
If you need any changes do let me know
Thanks

**Comment by rishipurwar1** [comment]
Hey @shreyaansjain06 
I'll review the pr soon.

Feel free to give a star to the repo

**Comment by shreyaansjain06** [comment]
yeah sure i will do
 I want to become part of your community and do valuable contributions even after hactobefest

**Comment by rishipurwar1** [comment]
> I want to become part of your community and do valuable contributions even after hactobefest

Great!
I already opened a couple of good issues, if you want, you can work on them.
