### ISSUE TITLE
Add a comment system to the solution detail page

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#69]
**Is your feature request related to a problem? Please describe.**
Right now, users can't get feedback on their solutions.

**Describe the solution you'd like**
Build a comment system, so, users can give their feedback on someone's solutions.

**Comment by Rispectech** [comment]
@rishipurwar1 can I work on this issue?

**Comment by akhilpamwani** [comment]
I can work much better than him

**Comment by rishipurwar1** [comment]
@akhilpamwani this is not a competition.
Opensource is about collaborating with other people.
Both of you can work on this issue.

**Comment by rishipurwar1** [comment]
@Rispectech are you working on this issue?

**Comment by Rispectech** [comment]
Sure I will work on this but can I start after a few days like on Tuesday. I am busy due to some previous appointment but I am interested in the project so would be extremely thankful if u can comply
Thanks

**Comment by rishipurwar1** [comment]
No Problem
Take your time🙂

**Comment by Rispectech** [comment]
Thanks a lot, @rishipurwar1. I will try to meet your expectations

**Comment by Rispectech** [comment]
hey, @rishipurwar1 I started today. I don't know much about TailwindCSS. so should I learn it and implement or do normal CSS and styled components work?

**Comment by rishipurwar1** [comment]
Tailwindcss is very similar to normal CSS like in normal CSS we write classes in the External CSS file and then add that class to our HTML file, similarly, Tailwindcss has already created those classes for us so that we can use them directly in our HTML(React Component).
Tailwindcss docs: https://tailwindcss.com/ (docs are really good, just search for a CSS property in the docs)
Tutorial: https://www.youtube.com/playlist?list=PL4cUxeGkcC9gpXORlEHjc5bgnIi5HEGhw

**Comment by rishipurwar1** [comment]
@Rispectech Can you please share a rough sketch of the comment system on Figma or somewhere else, so I can give you feedback on that before you start coding it.

**Comment by Rispectech** [comment]
I haven't made any design yet as I am not so familiar with Figma but I was thinking of something similar to youtube only with some of the features like reply and edit. if u have something in mind please guide me through 
this seems to be my current idea 
https://dribbble.com/shots/3564205-Comment-Section?utm_source=Clipboard_Shot&utm_campaign=Ky_Bridges&utm_content=Comment%20Section&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=Ky_Bridges&utm_content=Comment%20Section&utm_medium=Social_Share

**Comment by rishipurwar1** [comment]
Hello @Rispectech 

Here is design UI Design for comment section:

### Screen 1
![Screen-1](https://user-images.githubusercontent.com/57035408/136010443-9178a868-59e0-4441-8a78-796e3c80d56f.png)

### Screen 2
![Screen-2](https://user-images.githubusercontent.com/57035408/136010451-58b0b698-cd0a-4a01-b770-051d657f3a35.png)

### Screen 3
![Screen-3](https://user-images.githubusercontent.com/57035408/136010478-9514c5b3-7977-4174-9fa6-f09c179bf0b8.png)


Figma Design Link: https://www.figma.com/file/4KNz4sLFvH1305LUIdaPuq/comment-section?node-id=0%3A1

**Comment by rishipurwar1** [comment]
Use the gradient background color similar to the hero section instead of the solid purple(in the image) and make some changes in the like button. First try to finish the comment section then only add like functionality(I'll open a new issue for that), Like functionality is completely optional for now.

**Comment by rishipurwar1** [comment]
You can also see the prototype in Figma, how do these features work?

**Comment by Rispectech** [comment]
> Use the gradient background color similar to the hero section instead of the solid purple(in the image) and make some changes in the like button. First try to finish the comment section then only add like functionality(I'll open a new issue for that), Like functionality is completely optional for now.

Ohh okay I thought I had to add the functionality as well 
done for now I will complete the UI only

**Comment by Rispectech** [comment]
> You can also see the prototype in Figma, how do these features work?

sorry I couldn't understand your question . u want to know how will I execute the functionality or something else ?

**Comment by rishipurwar1** [comment]
> Ohh okay I thought I had to add the functionality as well

You also need to add the functionality.

**Comment by rishipurwar1** [comment]
> > You can also see the prototype in Figma, how do these features work?
> 
> sorry I couldn't understand your question . u want to know how will I execute the functionality or something else ?

I meant you can see the prototype of this feature on Figma how do these features work!
Something like this:

https://user-images.githubusercontent.com/57035408/136029660-db952829-51a1-4695-8bcd-1569b7898783.mov

**Comment by Rispectech** [comment]
> > > You can also see the prototype in Figma, how do these features work?
> > 
> > 
> > sorry I couldn't understand your question . u want to know how will I execute the functionality or something else ?
> 
> I meant you can see the prototype of this feature on Figma how do these features work! Something like this:
> 
>  Screen.Recording.2021-10-05.at.6.41.21.PM.mov

oh right yeah it's working for me. thanks and sorry for being such a trouble
and I wasn't able to see the cards info and I wanted to ask whether we can talk in discord as well or not 
thanks

**Comment by rishipurwar1** [comment]
> and I wanted to ask whether we can talk in discord as well or not

yes, we can but if it's related to the issue then I would suggest keeping all the discussion over here so that if someone wants to give a suggestion, they can easily give it.

**Comment by rishipurwar1** [comment]
If you have any doubt, feel free to discuss with us.

**Comment by rishipurwar1** [comment]
This feature is slightly complicated, so, plan things well before writing code. If you need any help from me, I would love to help you out.

**Comment by Rispectech** [comment]
yup that's alright it's just that with discord I can share the screen and we can communicate better but if that's not feasible then it's all right for me

**Comment by Rispectech** [comment]
> This feature is slightly complicated, so, plan things well before writing code. If you need any help from me, I would love to help you.

okay will do

**Comment by rishipurwar1** [comment]
> yup that's alright it's just that with discord I can share the screen and we can communicate better but if that's not feasible then it's all right for me

If you want to show something or discuss with me then it's completely fine to communicate with me through Discord.

**Comment by Rispectech** [comment]
Nope, I don't think so I have access to your DB. I will dm you in discord

**Comment by rishipurwar1** [comment]
> hey @rishipurwar1 actually i wanted to add some changes in the tailwind css but it was not working so i made some changes in tailwind.js and tailwind-config.js i replaced `purge = [ ]` with `purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],` in both tailwind.css and tailwind-config.css according to the docs is it acceptable ?

What do you want to achieve?

**Comment by Rispectech** [comment]
actually, I add some new width values. then used npm run build but changes weren't implemented 
so I searched up the docs and found that it was working after making the changes 
is there any other procedure to go through with tailwind?

**Comment by rishipurwar1** [comment]
@Rispectech any updates on this one?

**Comment by rishipurwar1** [comment]
> yep, I have completed the comment section and the comments and I think I may have figured out the functionality as well but not so sure about it. only the text box is left. just a little more time. I really struggled to set it up and trying to understand tailwind so it is taking a bit more than normal hope u can bear with me for bit more thanks

time is not an issue for me. I just wanted to know that you are working or not.
Take your time.

**Comment by Rispectech** [comment]
hey @rishipurwar1, I have made all the components according to the Figma design. I wanna discuss something about the functionality. so how can I do that? on discord or something else?

**Comment by likitarai1** [comment]
@rishipurwar1 Can I work on this issue?
