### ISSUE TITLE
Add a contributors section on the challenge details page

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#71]
**Is your feature request related to a problem? Please describe.**
Right now, we're not able to give proper credit to the challenge contributor.

**Describe the solution you'd like**
You need to build a contributor section on the challenge details page, so if someone contributes a new challenge design, we can give proper credit to them by linking their social profile.

**Screenshot**

<img width="1382" alt="Screenshot 2021-10-01 at 10 41 16 AM" src="https://user-images.githubusercontent.com/57035408/135568568-6d97f774-5327-4d86-b0b2-153cb613b36b.png">

**Comment by Bivas-Biswas** [comment]
@rishipurwar1 Hey, I want to work on this

**Comment by rishipurwar1** [comment]
@Bivas-Biswas assigned to you.

**Comment by piyush-harsh-15** [comment]
@rishipurwar1 hey can I work on this?

**Comment by rishipurwar1** [comment]
> @rishipurwar1 hey can I work on this?

Already assigned to @Bivas-Biswas 
Please select a different issue.

**Comment by Bivas-Biswas** [comment]
![image](https://user-images.githubusercontent.com/75929842/135657874-fc583a4c-3375-4fa9-ac84-ceba5f55ba33.png)
@rishipurwar1 design completed. just need to add dynamic data. Can you add the data to firebase.

**Comment by rishipurwar1** [comment]
> ![image](https://user-images.githubusercontent.com/75929842/135657874-fc583a4c-3375-4fa9-ac84-ceba5f55ba33.png) @rishipurwar1 design completed. just need to add dynamic data. Can you add the data to firebase.

Great work!
Will add data to the firebase tomorrow?
Please check this change on different screen sizes.
Can you please create a separate component for this, so we can reuse it in other places like solution cards and in solution detail page?

**Comment by Bivas-Biswas** [comment]
> > ![image](https://user-images.githubusercontent.com/75929842/135657874-fc583a4c-3375-4fa9-ac84-ceba5f55ba33.png) @rishipurwar1 design completed. just need to add dynamic data. Can you add the data to firebase.
> 
> Great work! Will add data to the firebase tomorrow? Please check this change on different screen sizes. Can you please create a separate component for this, so we can reuse it in other places like solution cards and in the solution detail page?

okay

**Comment by rishipurwar1** [comment]
> Also i will create this a separate component

Don't add "Contributed By" in the component, only include the profile data

**Comment by Bivas-Biswas** [comment]
I will add in smallcomponents folder , any name suggestion

**Comment by rishipurwar1** [comment]
> I will add in smallcomponents folder , any name suggestion for the components.

Maybe ContributorProfile.js

**Comment by Bivas-Biswas** [comment]
> > I will add in smallcomponents folder , any name suggestion for the components.
> 
> Maybe ContributorProfile.js

okay, i am done with my side. You need to just update the database.

**Comment by rishipurwar1** [comment]
> > > I will add in smallcomponents folder , any name suggestion for the components.
> > 
> > 
> > Maybe ContributorProfile.js
> 
> okay, i am done with my side. You need to just update the database.

Will do that soon.
When you add data using data to that component, please make sure you're are handling different use cases for example: let's say there is not any contributor for the particular challenge, so, you need to hide that section. You need to write a little bit js to do that(specifically ternary operator or && operator).

**Comment by Bivas-Biswas** [comment]
> > > > I will add in smallcomponents folder , any name suggestion for the components.
> > > 
> > > 
> > > Maybe ContributorProfile.js
> > 
> > 
> > okay, i am done with my side. You need to just update the database.
> 
> Will do that soon. When you add data using data to that component, please make sure you're are handling different use cases for example: let's say there is not any contributor for the particular challenge in the DB, so, you need to hide that section. You need to write a little bit js to do that(specifically ternary operator or && operator).

Great, I didn't think of this edge case.

**Comment by Bivas-Biswas** [comment]
I just completed from my side .
Just need the data.

Also add the Contributors any social media link. That would be very good. 
Then I will add a link hover with underline.  

There is no hurry. Just give some update. 🙂

**Comment by rishipurwar1** [comment]
> I just completed from my side . Just need the data.
> 
> Also add the Contributors any social media link. That would be very good. Then I will add a link hover with underline.
> 
> There is no hurry. Just give some update. 🙂

Actually, I am very busy these days, will let you know after updating the data

**Comment by rishipurwar1** [comment]
> I just completed from my side . Just need the data.
> 
> Also add the Contributors any social media link. That would be very good. Then I will add a link hover with underline.
> 
> There is no hurry. Just give some update. 🙂

I added the data.
and please use the Cloudinary Image component for the profile photo.

**Comment by Bivas-Biswas** [comment]
@rishipurwar1 close this issue

**Comment by rishipurwar1** [comment]
> @rishipurwar1 close this issue

I left a comment on your PR, please check
