### ISSUE TITLE
Bug: In challenge page Dropdown menu Mobile has no hover effect  

### ISSUE THREAD

**Issue by Bivas-Biswas** [rishipurwar1/coding-space#77]
**Describe the bug**
In Dropdown menu Desktop has a hover effect. But Mobile has no hover effect 

**To Reproduce**

1. Go to 'challenge page'
2. Click on 'Option Dropdown'
3. Hover to 'Mobile'
4. no Hover Effect 

**Expected behavior**
I want when I hover over the mobile, it's hover effect is same as desktop hover.

**Screenshots**
![image](https://user-images.githubusercontent.com/75929842/135667202-4e94a360-c980-47f9-b5aa-7573f68eaac0.png)

To

![image](https://user-images.githubusercontent.com/75929842/135667563-663537b1-3300-4f9e-93a3-809bc2271bb1.png)

**Desktop (please complete the following information):**

- OS: windows
- Browser : chrome
- Version  22

**Comment by Bivas-Biswas** [comment]
I want work on this.

**Comment by Manas-E** [comment]
Hey, @Bivas-Biswas  Can I try this out?

**Comment by Harshavardhan7678** [comment]
Hey @Bivas-Biswas, I would love to fix this bug. Kindly, assign it to me.

**Comment by rishipurwar1** [comment]
@Bivas-Biswas You can work on this issue.

**Comment by rishipurwar1** [comment]
Sorry @Manas-E @Harshavardhan7678 
@Bivas-Biswas First asked me, so, I have to assign to him

**Comment by Bivas-Biswas** [comment]
> @Bivas-Biswas You can work on this issue.

okay

**Comment by rishipurwar1** [comment]
Hey @Bivas-Biswas,

But don't add that white background on hover, come up with something good.

**Comment by Bivas-Biswas** [comment]
> Hey @Bivas-Biswas,
> 
> But don't add that white background on hover, come up with something good.

Do you want that desktop and mobile hover effects have same effect or difference.
Like, Currently desktop effect remain same. And add another effect for mobile

**Comment by rishipurwar1** [comment]
> Do you want that desktop and mobile hover effects have same effect or difference.

Same effect

And when desktop/mobile is selected, it should have an active state(just add bg color).

**Comment by rishipurwar1** [comment]
Before making a commit, please show me here, so, I can give you feedback on that.

**Comment by Bivas-Biswas** [comment]
I need to confirm that you need different bg color for both element

**Comment by rishipurwar1** [comment]
> I need to confirm just that you need different bg color for both element

No, you need to add the same bg color for both(mobile and desktop) on hover.
You will need to confirm that the design looks good after the changes you make.

**Comment by rishipurwar1** [comment]
and please make the PR on the development branch not in the main branch

**Comment by Shreyas-Waghchaure** [comment]
Is it still open for contribute

**Comment by Bivas-Biswas** [comment]
@Shreyas-Waghchaure  Hey, I am working on it. You can see other issue.

**Comment by Bivas-Biswas** [comment]
@rishipurwar1 

![image](https://user-images.githubusercontent.com/75929842/135726703-c56ca15d-4337-42fb-a446-bfa5deb03681.png)

with border-radius

![image](https://user-images.githubusercontent.com/75929842/135726745-631156f0-2be3-401b-8aba-683bdd9fbf08.png)

Good : 
1. It's match with the theme
2. Because It placed over the figma page. Lot's design doesn't  use bg-purple-500 as primary color. So from a user perspective  it would be a good UX.

**Comment by Shreyas-Waghchaure** [comment]
if there any other issue regarding UI please let me know to contribute @rishipurwar1

**Comment by rishipurwar1** [comment]
> @rishipurwar1
> 
> ![image](https://user-images.githubusercontent.com/75929842/135726703-c56ca15d-4337-42fb-a446-bfa5deb03681.png)
> 
> with border-radius
> 
> ![image](https://user-images.githubusercontent.com/75929842/135726745-631156f0-2be3-401b-8aba-683bdd9fbf08.png)
> 
> Good :
> 
> 1. It's match with the theme
> 2. Because It placed over the figma page. Lot's design doesn't  use bg-purple-500 as primary color. So from a user perspective  it would be a good UX.
> 
> @rishipurwar1 which is looked best with border or not ??

It looks great but use it without border-radius and one more thing removes that little padding-bottom or margin-bottom and see how it looks?

**Comment by rishipurwar1** [comment]
> if there any other issue regarding UI please let me know to contribute @rishipurwar1

Go through the website you'll find some UI bugs and keep your eye on the issues page. I'll try to add more issues soon.

**Comment by Bivas-Biswas** [comment]
@rishipurwar1 the drop down menu hide the full screen button. so I moved the option box left side.
It looks good for me.
give some feedback.
![image](https://user-images.githubusercontent.com/75929842/135827019-3b5daee3-2c9a-4401-8db5-e73cfdff7e4d.png)

**Comment by Bivas-Biswas** [comment]
> > @rishipurwar1
> > ![image](https://user-images.githubusercontent.com/75929842/135726703-c56ca15d-4337-42fb-a446-bfa5deb03681.png)
> > with border-radius
> > ![image](https://user-images.githubusercontent.com/75929842/135726745-631156f0-2be3-401b-8aba-683bdd9fbf08.png)
> > Good :
> > 
> > 1. It's match with the theme
> > 2. Because It placed over the figma page. Lot's design doesn't  use bg-purple-500 as primary color. So from a user perspective  it would be a good UX.
> > 
> > @rishipurwar1 which is looked best with border or not ??
> 
> It looks great but use it without border-radius and one more thing remove that little padding-bottom or margin-bottom and see how it looks?

I think no need remove that little padding-bottom.
![image](https://user-images.githubusercontent.com/75929842/135829561-00e65c9b-78f0-4305-864b-e8052caa71d0.png)

**Comment by Bivas-Biswas** [comment]
One more 
also changed icon when someone clicked to the option.
![image](https://user-images.githubusercontent.com/75929842/135830699-35ab99ba-98a8-421b-9fd0-811bebe87e5d.png)

![image](https://user-images.githubusercontent.com/75929842/135830725-9a964ae8-43c3-4333-ba01-cded7433647d.png)

**Comment by rishipurwar1** [comment]
> @rishipurwar1 the drop down menu hide the full screen button. so I moved the option box left side. It looks good for me. give some feedback. ![image](https://user-images.githubusercontent.com/75929842/135827019-3b5daee3-2c9a-4401-8db5-e73cfdff7e4d.png)

Looks good to me

**Comment by rishipurwar1** [comment]
> > > @rishipurwar1
> > > ![image](https://user-images.githubusercontent.com/75929842/135726703-c56ca15d-4337-42fb-a446-bfa5deb03681.png)
> > > with border-radius
> > > ![image](https://user-images.githubusercontent.com/75929842/135726745-631156f0-2be3-401b-8aba-683bdd9fbf08.png)
> > > Good :
> > > 
> > > 1. It's match with the theme
> > > 2. Because It placed over the figma page. Lot's design doesn't  use bg-purple-500 as primary color. So from a user perspective  it would be a good UX.
> > > 
> > > @rishipurwar1 which is looked best with border or not ??
> > 
> > 
> > It looks great but use it without border-radius and one more thing remove that little padding-bottom or margin-bottom and see how it looks?
> 
> I think no need remove that little padding-bottom. ![image](https://user-images.githubusercontent.com/75929842/135829561-00e65c9b-78f0-4305-864b-e8052caa71d0.png)

ok

**Comment by rishipurwar1** [comment]
> One more also changed icon when someone clicked to the option. ![image](https://user-images.githubusercontent.com/75929842/135830699-35ab99ba-98a8-421b-9fd0-811bebe87e5d.png)
> 
> ![image](https://user-images.githubusercontent.com/75929842/135830725-9a964ae8-43c3-4333-ba01-cded7433647d.png)

Open a new issue for this, don't commit all the changes in one pr
