### ISSUE TITLE
Add a more creative headline to the Homepage and style it

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#79]
**Describe an issue**
The text of the Hero section of the homepage doesn't look good, every line in that text looks very close.

**Describe the solution you'd like**
Add a more creative headline to the Hero section and style it properly, play with letter spacing and line-height property to give proper spacing and you can also increase the width of the text container, there are so many ways to make it look good on different screens sizes. You are limited only by your imagination.

**Screenshots**
<img width="675" alt="Screenshot 2021-10-02 at 7 41 44 AM" src="https://user-images.githubusercontent.com/57035408/135700856-f61bfb89-f18f-4b04-bbbc-81ca07244d2d.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome

**Comment by demonicirfan** [comment]
Hii can i work on this for hacktober fest

**Comment by rishipurwar1** [comment]
@demonicirfan assigned to you.
Please share the new headline with me, before committing your changes.

**Comment by demonicirfan** [comment]
![image](https://user-images.githubusercontent.com/74172466/136087707-918f2a52-6e81-4609-81be-629b7d949a7e.png)
does this look good to you

**Comment by demonicirfan** [comment]
I have played with spaceing line height and width still got to figure out how can i make it look good. Just need your feedback

**Comment by rishipurwar1** [comment]
> @rishipurwar1 can you please tell about this headline, how can i improve this i need some feedback

Will review it soon
