### ISSUE TITLE
Add a more creative headline to the Challenges Page and style it

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#82]
**Describe an issue**
The text of the Hero section of the Challenges page doesn't look good, every line in that text looks very close.

**Describe the solution you'd like**
Add a more creative headline to the Hero section and style it properly, play with letter spacing and line-height property to give proper spacing and you can also increase the width of the text container, there are so many ways to make it look good on different screens sizes. *You are limited only by your imagination*.

**Screenshots**
<img width="675" alt="Screenshot 2021-10-02 at 8 01 14 AM" src="https://user-images.githubusercontent.com/57035408/135701078-522ec2e3-a839-42af-90b0-e4e6d40edcf1.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome

**Comment by aman-sukhwal-7** [comment]
I can work on it!

**Comment by rishipurwar1** [comment]
@aman-sukhwal-7 assigned to you

**Comment by imps1001** [comment]
Can I also work on it

**Comment by rishipurwar1** [comment]
> Can I also work on it

yes you can work on this one.
