### ISSUE TITLE
Add a more creative headline to the MySolutions Page and style it

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#83]
**Describe an issue**
The text of the Hero section of the **MySolutions** page doesn't look good, every line in that text looks very close.

**Describe the solution you'd like**
You need to come up with a creative headline for the Hero section of the MySolutions page and replace it with the existing headline and style it properly, play with letter spacing and line-height property to give proper spacing and you can also increase the width of the text container, there are so many ways to make it look good on different screens sizes. You are limited only by your imagination.

**Screenshots**
<img width="675" alt="Screenshot 2021-10-02 at 8 02 52 AM" src="https://user-images.githubusercontent.com/57035408/135701117-d88e241b-703d-43d1-ba80-219b8d65985a.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome

**Comment by shikhar13012001** [comment]
Hey! I would like to work on this, could you assign this to me?

**Comment by rishipurwar1** [comment]
@shikhar13012001 assigned to you.
Please share the new headline with me, before committing your changes.

**Comment by Paawan9700** [comment]
hey kindly assign this issue to me, i will surely try to resolve it.

**Comment by rishipurwar1** [comment]
@shikhar13012001 are you working on this issue?

**Comment by rishipurwar1** [comment]
> hey kindly assign this issue to me, i will surely try to resolve it.

Hello @Paawan9700 👋
Welcome to the CODINGSPACE community,🚀

If you have some creative headline for this page, you can share with us.

**Comment by rishipurwar1** [comment]
@Paawan9700 @shikhar13012001 any updates?

**Comment by Harshavardhan7678** [comment]
Hey @rishipurwar1, I would like to work on this as well.
The headlines I would suggest are:

1. Looking for solutions? You have come to the right page!
2. There you go. All the solutions you need are right here. 
3. Take a look around. Here are your solutions. 
4. Do help yourselves with all the solutions available.
Kindly suggest to me which you feel might be best, and I will start working on it.

**Comment by rishipurwar1** [comment]
@Harshavardhan7678 great headlines. But this is "my solutions" page means this page is only available to the user that submitted those solutions.
this line is good(Take a look around. Here are your solutions.) but improve it a little bit something like "All your hard work lives here. Take a look around. Here are your solutions." Try to improve it and make a pr.

**Comment by rishipurwar1** [comment]
Yes! add this line and first send me ss of different screen sizes.
