### ISSUE TITLE
Bug : side navbar icons are not center in screen size between 1024-1279

### ISSUE THREAD

**Issue by Bivas-Biswas** [rishipurwar1/coding-space#87]
**Describe the bug**
side option icons are not center in screen size between 1024-1279.
It needs to center the div.

**To Reproduce**
Center the icon

1. Open 'Screen between 1024-1279'
2. check 'side navbar'
4. See error 'icon not center'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75929842/135728325-6b20615c-51d4-4ded-9f81-f6ec94d6e5c8.png)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome, Firefox, Brave]

**Comment by arp99** [comment]
I have added a PR for this issue, kindly please review it

**Comment by rishipurwar1** [comment]
Hey @arp99 
Great work
Please test it for all screen sizes and add a screenshot of the changes. It should be at the left when the screen size is large

**Comment by arp99** [comment]
Hey @rishipurwar1 Here are the scrrenshots for sm,md,lg,xl screen sizes
![3](https://user-images.githubusercontent.com/47218246/135742153-f863f9b1-1f18-4da0-83e2-490dee905d42.jpg)
![4](https://user-images.githubusercontent.com/47218246/135742156-8a0b7081-2c2a-4c42-8635-c5274322a35b.jpg)
![1](https://user-images.githubusercontent.com/47218246/135742157-67262eff-293f-4af8-9692-e586a6dbe271.jpg)
![2](https://user-images.githubusercontent.com/47218246/135742158-40cbedec-ed8a-4ff2-a1be-7572341da48d.jpg)

Kindly review the PR : #88
