### ISSUE TITLE
Design a Roadmaps page

### ISSUE THREAD

**Issue by rishipurwar1** [rishipurwar1/coding-space#90]
**Is your feature request related to a problem? Please describe.**
Right now, we don't have a roadmaps page.

**Describe the solution you'd like**
Design a roadmap using a similar design system.
- [ ] Roadmap page should have a hero section like all other pages
- [ ] Roadmap page should have four types of roadmaps(Frontend Path, Backend Path, Full-stack Path, Mobile Development path)
- [ ] When users click on one of these paths, they can see related challenges to that path.

Use your creativity to design this page, You are limited only by your imagination.

**Comment by kamyaakash** [comment]
hello, can you assign this to me?

**Comment by rishipurwar1** [comment]
@kamyaakash assigned to youl

**Comment by kamyaakash** [comment]
Thank you, actually I came here through your youtube. is there any way I can contact you for some queries?

**Comment by rishipurwar1** [comment]
Hello @kamyaakash 
Welcome to the CODINGSPACE community🚀
If you have queries related to this issue, then I would recommend you to ask your queries here.
If you have some personal query then you can join our Discord Community and dm me over there, you can also message me on [LinkedIn](https://www.linkedin.com/in/thefierycoder/) or [Twitter](https://twitter.com/thefierycoder).

**Comment by DarkSoul26** [comment]
@rishipurwar1 can you please assign this issue to me?

**Comment by rishipurwar1** [comment]
@DarkSoul26 any updates on this?

**Comment by DarkSoul26** [comment]
Hey @rishipurwar1 the cards section is not visible to me and maybe I know the reason. It is because I have used my credentials for firebase storage not yours.

Can you suggest any solution so that I can see the cards in all the sections?

**Comment by rishipurwar1** [comment]
@DarkSoul26 just gave you access
