### ISSUE TITLE
View challenges button does not fix to the bottom of card

### ISSUE THREAD

**Issue by arp99** [rishipurwar1/coding-space#93]
**Describe the bug**
In the challenges card, in some cards the view challenges button does not come to the end, it leaves some space at the bottom

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the website
2. Try resizing the window
3.  You will see the error as the screenshot

**Expected behaviour**
All view challenge buttons should be fixed at the bottom 

**Screenshots**

![issue_by_me](https://user-images.githubusercontent.com/47218246/135759475-0d713b08-85e9-447c-9461-990a915dc960.png)
**Desktop (please complete the following information):**

- OS: windows
- Browser Chrome
- Version 22

**Comment by arp99** [comment]
@rishipurwar1 Please assign me this issue I want to work on this, For this I would need the data from your firebase database, Otherwise The card would just show skeleton UI for me.

**Comment by arp99** [comment]
@rishipurwar1 I need the data of the cards to view , otherwise it is just showing skeleton UI in localhost

**Comment by rishipurwar1** [comment]
Share your email over here or you can dm me on Twitter or on our discord server.

**Comment by arp99** [comment]
> Share your email over here or you can dm me on [Twitter](https://twitter.com/thefierycoder) or on our discord server.

Check your DM

**Comment by arp99** [comment]
@rishipurwar1 Please review the PR #101

**Comment by arp99** [comment]
The resources card also had a similar issue, so I am pushing the commits in this PR only
![same_issue_resources](https://user-images.githubusercontent.com/47218246/135771296-d9d7cd36-4c95-4fd2-9dd2-42930a776a58.png)

**Comment by rishipurwar1** [comment]
Please open a new issue for the resource card and make a separate PR

**Comment by rishipurwar1** [comment]
> @rishipurwar1 Please review the PR #101

will review it

**Comment by MrM-7** [comment]
Hey! Can you assign this to me ? I will fix it.

**Comment by arp99** [comment]
> Please open a new issue for the resource card and make a separate PR

I will make it in soon, by resetting the last commit, sorry for late reply

**Comment by arp99** [comment]
> Please open a new issue for the resource card and make a separate PR

I have added a separate PR for that kindly, please review it

**Comment by rishipurwar1** [comment]
> > Please open a new issue for the resource card and make a separate PR
> 
> I have added a separate PR for that kindly, please review it

will review it by tomorrow. I have a lab exam tomorrow

**Comment by rishipurwar1** [comment]
> Hey! Can you assign this to me ? I will fix it.

this issue is already taken by @arp99, you can pick different issues from the issue page or create your own, you can easily find some UI bugs on the website but please take confirmation from me before solving the bug.
